export const ALREADY_CONNECTED = "ALREADY_CONNECTED";
export const ERROR_NOT_CONNECTED = "NOT_CONNECTED";
export const NOT_SUPPORTED_COLUMN = "NOT_SUPPORTED_COLUMN";
export const QUERY_NOT_PROCESSED = "QUERY_NOT_PROCESSED";
export const BAD_FORMAT_QUERY = "BAD_FORMAT_QUERY";
export const OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND";
